default_platform(:android)

 lane :qa do |options|
    branch = options[:branch]
    release = options[:release]
    tester = options[:tester]
    group = options[:group]
    flavour = options[:flavour]
    checkout_branch(branch)
  end

   def checkout_branch(branch)
      puts message: branch
      sh "git fetch origin " + branch
      sh "git checkout " + branch
      sh "git reset --hard origin/" + branch
    end

end
