default_platform(:android)

platform :android do

$production_flavour = "production"

 ensure_git_status_clean
  lane :build do |options|
    flavor = options[:flavor]
    build_type = options[:type]
    task = options[:task]
    gradle(
      task: "clean"
    )
    gradle(
      task: task,
      build_type: build_type,
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "android-certificate.jks",
        "android.injected.signing.store.password" => "test123",
        "android.injected.signing.key.alias" => "android-fastlanetest",
        "android.injected.signing.key.password" => "test123",
      }
    )
  end

 lane :qa do |options|
    branch = options[:branch]
    release = options[:release]
    tester = options[:tester]
    group = options[:group]
    flavour = options[:flavour]
    checkout_branch(branch)
     if flavour == nil
          flavour = "release"
        end
    build(flavor: flavour, type: "Release", task: "assemble")
  end

   def checkout_branch(branch)
      puts message: branch
      sh "git fetch origin " + branch
      sh "git checkout " + branch
      sh "git reset --hard origin/" + branch
    end

end
